config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
    resources :notes

  authenticated :user do
    root 'notes#index', as: 'root_for_authed_user'
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @notes = Note.where(user_id: current_user).order('created_at desc')
  end

  def show

  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
    def find_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Deathnote
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header_inner
        = link_to image_tag('logo.png'), root_path, id: 'logo'
        %nav
          -if user_signed_in?
            = link_to 'New Note', new_note_path
            = link_to 'Logout', destroy_user_session_path, method: :delete
          -else
            = link_to 'Log In', new_user_session_path
    %p.notice= notice
    %p.alert= alert

    =yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: 'button'

app/views/notes/edit.html.haml
.wrapper_with_padding
  %h1
    Edit Note
  = render 'form'
  = link_to 'Cancel', @note

app/views/notes/index.html.haml
.wrapper_with_padding
  #notes.clearfix
    - unless @notes.blank?
      -@notes.each do |note|
        %a{href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date
              = time_ago_in_words(note.created_at)
              ago
    - else
      %h2 Add a note
      %p Looks like you do not have any note yet. Go ahead and write one :)
      = link_to 'New Note', new_note_path, class: 'btn'

app/views/notes/new.html.haml
.wrapper_with_padding
  %h1
    Add New Note
  = render 'form'

app/views/notes/show.html.haml
.wrapper_with_padding
  #note_show
    %h1.title= @note.title
    %p= simple_format(@note.content)
    .buttons
      =link_to 'All Notes', notes_path, class: 'button'
      =link_to 'Edit', edit_note_path(@note), class: 'button'
      =link_to 'Delete', note_path(@note), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button'

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Deathnote
    %p
      Your last words in our database...
      %br/
      %br/
      %br/
      = link_to 'Sign Up', new_user_registration_path, class: 'btn'
#testimonial
  .wrapper
    %p.quote "An awesome place to keep you notes before dying.
    %p.quote We care about our clients..."
    %p.name - Deathnote LLC
#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Notes
        %p 4:30 p.m.  The subway train draws to a halt. There is no station in sight. Anxious glances dart around about the passengers as they realize each others presence for the first time...
      .callout
        %h2 Memories
        %p At the end of the train, a young lady in a green pants suit stands up in the middle of the car and starts to unbutton her jacket, which she takes off and drops to the dirty floor....
      .callout
        %h2 Secret Wishes
        %p She also takes off her shoes, her pants, her blouse, and the rest of her undergarments dropping them into a neat little pile.  This leaves her totally naked...
#bottom_cta
  .wrapper
    %h2 Sign up already
    %p Do not die without you note in our server...
    = link_to 'Click me or die trying', new_user_registration_path, class: 'btn'
%footer
  %p &copy; Created and Powered by Mher Margaryan